spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gesMakiti?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081

flickr:
  apiKey: 5c8f8d356f51c43cd4737ec132c86263
  apiSecret: 057525485ae941d2
  appKey: 72157720888275469-f6203c7d8159acdb
  appSecret: 20ad9d25f683adb8