spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gesMakiti?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
